name: Build and Publish @renewx/core
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: NPM install
        run: npm ci

      - name: Build NPM package
        run: npm run build

      - name: Copy LICENSE
        run: cp LICENSE packages/core/LICENSE

      - name: Save package artifacts
        uses: actions/upload-artifact@v3
        with:
          name: core-package-artifacts
          path: |
            packages/core/dist/index.*
            packages/core/dist/src
            packages/core/package.json
            packages/core/LICENSE
            packages/core/README.md

  publish:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: core-package-artifacts

      - name: Publish NPM package
        run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN_PUBLIC }}
